/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class AppAssets {
  static const String icAppIcon = "assets/svgs/ic_splash.svg";
  static const String icSplash = "assets/images/ic_splash.png";
}
